[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
linker = "aarch64-none-elf-ld"
rustflags = [
  "-C", "link-arg=-Tsrc/arch/aarch64/linker.ld",
  "-C", "relocation-model=static",
  "-C", "panic=abort",
  "-C", "link-arg=-z", "-C", "link-arg=max-page-size=0x1000",
  "-C", "link-arg=--nostdlib",
]
